#!/usr/bin/perl

use 5.010;
use warnings;

use lib 'lib';
use Plesk::Email::Manager::MakeConfig;

my $sr = Plesk::Email::Manager::MakeConfig->new(
    configfile => 'files/spamrelease.conf',
);

$sr->_fetch_all;


