#!/usr/bin/perl

use 5.010;
use warnings;

use lib 'lib';
use Plesk::Email::Manager::MakeConfig;

my $make_config = Plesk::Email::Manager::MakeConfig->new(
    configfile => 'files/spamrelease.conf',
);

$make_config->run;


